<?php
/**
 * Docmed theme setup.
 *
 * Docmed is a block theme: the layout lives in templates/*.html, the design
 * system in theme.json (generated by .dev/build_theme.py), and the sections in
 * patterns/*.php (generated by .dev/build_patterns.py). This file carries only
 * what those cannot express — supports flags, asset enqueues, block styles,
 * pattern categories, and the modules in inc/.
 *
 * @package Docmed
 */

defined( 'ABSPATH' ) || exit;

define( 'DOCMED_VERSION', '1.0.1' );

/**
 * Theme supports.
 */
function docmed_setup() {
	load_theme_textdomain( 'docmed', get_template_directory() . '/languages' );

	add_theme_support( 'title-tag' );
	add_theme_support( 'post-thumbnails' );
	add_theme_support( 'automatic-feed-links' );
	add_theme_support( 'html5', array( 'search-form', 'comment-form', 'comment-list', 'gallery', 'caption', 'style', 'script' ) );
	add_theme_support( 'editor-styles' );
	add_theme_support( 'responsive-embeds' );
	add_theme_support( 'align-wide' );
	add_theme_support( 'wp-block-styles' );
	add_theme_support(
		'custom-logo',
		array(
			'height'      => 45,
			'width'       => 163,
			'flex-height' => true,
			'flex-width'  => true,
		)
	);

	// style.css is loaded into the editor canvas too, so the components below
	// look the same there as on the front end.
	add_editor_style( 'style.css' );
}
add_action( 'after_setup_theme', 'docmed_setup' );

/**
 * Front-end styles.
 */
function docmed_enqueue_styles() {
	// The theme's own stylesheet by its template path, not get_stylesheet_uri():
	// under a child theme that returns the CHILD's style.css, and every
	// component style here would silently go missing.
	wp_enqueue_style( 'docmed-style', get_template_directory_uri() . '/style.css', array(), DOCMED_VERSION );
}
add_action( 'wp_enqueue_scripts', 'docmed_enqueue_styles' );

/**
 * Block style variations.
 *
 * Registered here rather than in theme.json because a style variation needs a
 * label for the editor's Styles panel. The CSS behind each one lives in
 * style.css, which always loads: a `style_handle` only enqueues while WordPress
 * serves separate block assets, and any plugin can switch that off site-wide.
 * .dev/dead-selectors.py fails the build if one of these has no CSS.
 */
function docmed_register_block_styles() {
	$styles = array(
		'core/heading'      => array(
			array( 'docmed-bar', __( 'Title with bar', 'docmed' ) ),
			array( 'docmed-kicker', __( 'Underlined kicker', 'docmed' ) ),
		),
		'core/group'        => array(
			array( 'docmed-card', __( 'Card', 'docmed' ) ),
			array( 'docmed-doctor', __( 'Doctor card', 'docmed' ) ),
			array( 'docmed-panel', __( 'Pale panel', 'docmed' ) ),
			array( 'docmed-form-box', __( 'Form box', 'docmed' ) ),
		),
		'core/button'       => array(
			array( 'docmed-outline', __( 'Outline (on colour)', 'docmed' ) ),
			array( 'docmed-ghost', __( 'Outline', 'docmed' ) ),
		),
		'core/list'         => array(
			array( 'docmed-checks', __( 'Ticks', 'docmed' ) ),
		),
		'core/social-links' => array(
			array( 'docmed-plain', __( 'Plain icons', 'docmed' ) ),
			array( 'docmed-squares', __( 'Squares', 'docmed' ) ),
		),
	);

	foreach ( $styles as $block => $variations ) {
		foreach ( $variations as $variation ) {
			list( $name, $label ) = $variation;
			register_block_style(
				$block,
				array(
					'name'  => $name,
					'label' => $label,
				)
			);
		}
	}
}
add_action( 'init', 'docmed_register_block_styles' );

/**
 * Scroll reveals, the reviews slider, the doctors carousel, the tabs, the
 * appointment dialog and the header's shadow once the page scrolls.
 *
 * Deferred and in the footer: everything the script does is an enhancement, so
 * it never needs to hold up rendering. `docmed_enable_scroll_animations`
 * switches off the reveals and leaves the rest, which is behaviour rather than
 * decoration.
 *
 * The settings go in as JSON, not through wp_localize_script(), which turns
 * `false` into an empty string that the script would read as "on".
 */
function docmed_enqueue_interactions() {
	wp_enqueue_script(
		'docmed-interactions',
		get_template_directory_uri() . '/assets/js/interactions.js',
		array(),
		DOCMED_VERSION,
		array(
			'in_footer' => true,
			'strategy'  => 'defer',
		)
	);

	wp_add_inline_script(
		'docmed-interactions',
		'window.docmedMotion = ' . wp_json_encode(
			array(
				'enabled'     => (bool) apply_filters( 'docmed_enable_scroll_animations', true ),
				/* translators: %d: slide number. */
				'slideLabel'  => __( 'Show review %d', 'docmed' ),
				'sliderLabel' => __( 'Patient reviews', 'docmed' ),
				'prevLabel'   => __( 'Previous doctors', 'docmed' ),
				'nextLabel'   => __( 'More doctors', 'docmed' ),
			)
		) . ';',
		'before'
	);
}
add_action( 'wp_enqueue_scripts', 'docmed_enqueue_interactions' );

/**
 * Pattern categories.
 */
function docmed_register_pattern_categories() {
	$categories = array(
		'docmed-sections' => array(
			'label'       => __( 'Docmed: sections', 'docmed' ),
			'description' => __( 'Full-width sections for building pages.', 'docmed' ),
		),
		'docmed-pages'    => array(
			'label'       => __( 'Docmed: pages', 'docmed' ),
			'description' => __( 'Complete page layouts.', 'docmed' ),
		),
	);

	foreach ( $categories as $slug => $args ) {
		register_block_pattern_category( $slug, $args );
	}
}
add_action( 'init', 'docmed_register_pattern_categories' );

/**
 * Expand shortcodes in a Shortcode block rendered by a template.
 *
 * core/shortcode's render callback only runs wpautop(); the expansion comes from
 * do_shortcode on `the_content`, which does not run for a block template or a
 * template part. The sidebar's newsletter form lives in a template part, so
 * without this it would print `[docmed_form …]` as text. Running
 * do_shortcode on already-expanded output is a no-op, so this is safe on
 * post content too.
 *
 * @param string $content Rendered block.
 * @return string
 */
function docmed_render_shortcode_block( $content ) {
	return do_shortcode( $content );
}
add_filter( 'render_block_core/shortcode', 'docmed_render_shortcode_block' );

require get_template_directory() . '/inc/front-page-setup.php';
require get_template_directory() . '/inc/appointment.php';
require get_template_directory() . '/inc/forms.php';
require get_template_directory() . '/inc/woocommerce.php';
require get_template_directory() . '/inc/scheme.php';
require get_template_directory() . '/inc/updates.php';
